print-progress: true
concurrent: 20
timeout: 5000
min-speed: 1
download-mb: 1

rename-node: true
node-prefix: " @小A科技分享 |"

# 强制本地当前目录
save-method: local
output-dir: "output"
output-formats:
  - yaml
  - base64

# 读取 main.py 生产的文件
sub-urls:
  - "./nodes.txt"
