name: 小A科技分享-全自动工厂

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签入代码
        uses: actions/checkout@v4

      - name: 安装 Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装必要插件
        run: |
          pip install requests

      - name: 执行洗货脚本
        # 【注意】这里必须确保你仓库里有个文件叫 main.py
        run: python main.py

      - name: 自动化提交更新
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚀 精华节点已更新 (Node 24 环境)"
          file_pattern: 'output/*'
