name: 小A全自动洗货工厂
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  factory-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1. 拉取仓库代码
        uses: actions/checkout@v4

      - name: 2. 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. 执行 Python 进货
        run: |
          pip install PyYAML requests
          python main.py

      - name: 4. 执行 subs-check 洗货 (测速+重命名)
        uses: beck-8/subs-check@master
        # 此时它会自动读取根目录的 config.yaml

      - name: 5. 将精华版推送到 output 文件夹
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚀 精华节点已出货"
          file_pattern: 'output/*'
